### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by hzlmn** [arthurvr/repo-exists#3]
Also, small suggestion...

 You have  like ton of open source modules, so maybe you're gonna like tool called [Hound](https://github.com/thoughtbot/hound) by  [thoughtbot](https://github.com/thoughtbot). 

So, what it does, it watches your repo by checking code styles, that you set and writes comments on pull requests and issues (if they don't match with code styles) how to fix it. It uses JSHint for checking , so you can specify whatever you want.

**Comment by arthurvr** [comment]
Thanks for the suggestion, but no thanks.

I have enough with JSCS (probably I'm going to switch to ESLint in the near future) and my eyes. Those bots are way to noisy imho. Also, it can't be a really fun experience as a first-time contributor to have a bot complaining about your code.

Thanks for the suggestion though. This reminds me that I should create an AMA repo one day too :p

**Comment by hzlmn** [comment]
Yeah, it would be great :+1:

**Comment by arthurvr** [comment]
@drKraken There you go sir! https://github.com/arthurvr/ama

**Comment by hzlmn** [comment]
@arthurvr :sparkles: nice
